rest:
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /rest

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    options:
        expose: true
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

