#    rest.example:
#        class: RestBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    restbundle.util.inflector:
      class: RestBundle\Util\Inflector\NoopInflector
    foreignHandler:
          class:     RestBundle\Serializer\ForeignKeyHandler
          tags:
              - { name: jms_serializer.subscribing_handler }